<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<ItemGroup Label="ProjectConfigurations"><ProjectConfiguration Include="Release|x64"><Configuration>Release</Configuration><Platform>x64</Platform></ProjectConfiguration></ItemGroup>
<PropertyGroup Label="Globals"><WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion></PropertyGroup>
<Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
<PropertyGroup Label="Configuration"><ConfigurationType>Application</ConfigurationType><PlatformToolset>v143</PlatformToolset></PropertyGroup>
<Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
<PropertyGroup><OutDir>$(ProjectDir)..\..\build\tests\zombies\bin\</OutDir><IntDir>$(ProjectDir)..\..\build\tests\zombies\obj\</IntDir></PropertyGroup>
<ItemDefinitionGroup><ClCompile><LanguageStandard>stdcpp20</LanguageStandard><ExceptionHandling>Sync</ExceptionHandling><AdditionalIncludeDirectories>$(ProjectDir)shim;$(ProjectDir)..\..\src\client;$(ProjectDir)..\..\src\common;$(ProjectDir)..\..\deps\rapidjson\include;$(ProjectDir)..\..\deps\libtomcrypt\src\headers</AdditionalIncludeDirectories><PreprocessorDefinitions>LTC_NO_FAST;LTC_NO_PROTOTYPES;LTC_NO_RSA_BLINDING;%(PreprocessorDefinitions)</PreprocessorDefinitions><RuntimeLibrary>MultiThreaded</RuntimeLibrary></ClCompile><Link><AdditionalLibraryDirectories>$(ProjectDir)..\..\build\bin\x64\Release</AdditionalLibraryDirectories><AdditionalDependencies>common.lib;libtomcrypt.lib;%(AdditionalDependencies)</AdditionalDependencies></Link></ItemDefinitionGroup>
<ItemGroup><ClCompile Include="zombies.cpp"/><ClCompile Include="../../src/client/game/demonware/hq_marketplace.cpp"/><ClCompile Include="../../src/client/game/demonware/byte_buffer.cpp"/><ClCompile Include="../../src/client/game/demonware/hq_economy.cpp"/><ClCompile Include="../../src/client/game/demonware/achievement_engine.cpp"/><ClCompile Include="../../src/client/game/demonware/achievement_response.cpp"/><ClCompile Include="../../src/client/game/demonware/reward_game_event.cpp"/></ItemGroup>
<Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" /></Project>